### ISSUE TITLE
Have you considered an Atom package?

### ISSUE THREAD

**Issue by uberhacker** [mglaman/conductor#22]
Since this project is built on [Electron](http://electron.atom.io/), what are your thoughts of creating an [Atom](https://atom.io/) package?  [Atom](https://atom.io/) is increasingly becoming one of the more popular open source text editors and is also built on [Electron](http://electron.atom.io/) so I imagine integrating a package would be relatively easy?

**Comment by mglaman** [comment]
@uberhacker I thought about first writing a PhpStorm plugin because it has rudimentary support and is a popular IDE for PHP developers. I had then possibly considered Atom.

Then there is the problem where there are people who also use Sublime Text. 

Writing a text editor / IDE specific plugin involved locking out users. I'd like to work on this to build abstracted components and then provide specific editor/IDE integrations. 

As you said, Electron (atom-shell) was built as the base for Atom. So whatever gets developed here could easily be ported into an Atom package.

Also an atom package would be a lot easier given it'd be "Shift CMD P: Composer install" etc

**Comment by mglaman** [comment]
I did some quick searches and there is:

* https://atom.io/packages/composer

What do you think an Atom package would provide beyond shortcuts to running the commands?

**Comment by uberhacker** [comment]
@mglaman: Thanks for the quick response.  What does that package provide other than a shell to non-interactive composer commands?  I think your project has much more to offer over this simple package.

**Comment by mglaman** [comment]
@uberhacker oh you mean a full GUI inside of Atom as a package? not just a shortcut to shell commands? How do you think that would look, or have any examples?

**Comment by uberhacker** [comment]
@mglaman: Not sure, I was just posing the possibility of integrating it into Atom.  I imagine providing a package in Atom would be easier than PHP Storm, Sublime Text, etc?  Might be worth considering targeting Atom first since the effort would be less, I would think?

**Comment by mglaman** [comment]
Well PhpStorm has some nice UI runners for Grunt and Npm, that was my goal there.

Atom would be easier because it is all JavaScript. I've done IntelliJ platform plugin work. Sublime Text would probably never happen because I suck at python :P

I just don't know how it'd look inside of Atom. Just take the standalone and embed it?

**Comment by uberhacker** [comment]
Your call.  I'm sure you are much better equipped that I am in this regard. :)

**Comment by borisson** [comment]
I really don't think we should be doing this, as it creates a bunch of work for matt whenever any of the supported editors change their API's. It also creates an additional dependency and I think the beauty of this solution is that it's a small and standalone package.

I'd suggest closing this issue because of those reasons.

**Comment by mglaman** [comment]
Yeah I'm going to close this. My hope is that JetBrains builds out the Composer GUI in PhpStorm. 

The main problem here is that I don't use any of these proposed tools. In perfectly fine typing my few commands in the command line. So it's spread effort others will hopefully be inspired to work on.
